### ISSUE TITLE
Build romana faild

### ISSUE THREAD

**Issue by feifeixyz** [ceph/romana#10]
I try to build the romana master branch, and this the error message. 

```
Running "concurrent:dist" (concurrent) task
>> Warning: There are more tasks than your concurrency limit. After this limit
>> is reached no further tasks will be run until the current tasks are
>> completed. You can adjust the limit in the concurrent task options

    Loading "connect_proxy.js" tasks...ERROR
    >> TypeError: Cannot read property 'prototype' of undefined

    Running "copy:styles" (copy) task


    Done, without errors.


    Execution Time (2016-07-01 04:50:45 UTC)
    loading tasks   8ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 31%
    copy:styles    17ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 65%
    Total 26ms
        Warning: Loading "connect_proxy.js" tasks...ERROR
    >> TypeError: Cannot read property 'prototype' of undefined

    Running "compass:dist" (compass) task
    Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

    Aborted due to warnings.


    Execution Time (2016-07-01 04:50:45 UTC)
    loading tasks   8ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 27%
    compass:dist   21ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 70%
    Total 30ms Use --force to continue.

        Aborted due to warnings.


Execution Time (2016-07-01 04:50:41 UTC)
git-describe:git.js  50ms  ▇ 1%
concurrent:dist      4.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
Total 4.7s
make[1]: *** [build-stamp] Error 6
make[1]: Leaving directory `/root/romana/manage'
make: *** [build-ui] Error 2
```

I already installed the ruby and compass packages.

**Comment by zphj1987** [comment]
change  romana/manage/package.json

``` bash
"grunt-connect-proxy":"xxxxxx"
```

to

``` bash
"grunt-connect-proxy": "~0.2.0"
```

and try again

**Comment by kivis-online** [comment]
Maybe your sudo PATH is not right.
I do it like this :  sudo env PATH=$PATH make build-real

But I have a new issue:

```
Warning:
/home/ceph/romana/manage/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
Error: ENOENT, no such file or directory 'dist/images/logo.png'
    at Object.fs.statSync (fs.js:696:18)
    at processed (/home/ceph/romana/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:84:43)
    at /home/ceph/romana/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:131:29
    at callDone (/home/ceph/romana/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:5)
    at ChildProcess.<anonymous> (/home/ceph/romana/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12) Use --force to continue.

    Aborted due to warnings.
```

**Comment by zphj1987** [comment]
Running "compass:dist" (compass) task
    Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

i do:
cp /usr/local/bin/compass /sbin/

---

@kivis-online 
i know this problem , it is the version of grunt-contrib-compass's problem，because the 0.5 have a bug,so you can change the package.json,and everything will ok

cd romana
change  grunt-contrib-imagemin version to 0.4.1

``` bash
[root@calamarimake romana]# grep "grunt-contrib-imagemin" -R *
admin/package.json: "grunt-contrib-imagemin": "~0.1.4",
dashboard/package.json: "grunt-contrib-imagemin": "0.1.4",
login/package.json: "grunt-contrib-imagemin": "~0.1.3",
manage/package.json: "grunt-contrib-imagemin": "~0.3.0",
```

change to ：

``` bash
admin/package.json: "grunt-contrib-imagemin": "0.4.1",
dashboard/package.json: "grunt-contrib-imagemin": "0.1.4",
login/package.json: "grunt-contrib-imagemin": "0.4.1",
manage/package.json: "grunt-contrib-imagemin": "0.4.1",
```

and continue···
