### ISSUE TITLE
make build-real failed

### ISSUE THREAD

**Issue by dotSlashLu** [ceph/romana#15]
`make build-real` failed with the following error:
```
Running "git-describe:git.js" (git-describe) task
/root/romana/manage/node_modules/.npminstall/tmp/0.0.21/tmp/lib/tmp.js:261
  throw err;
  ^

TypeError: Path must be a string. Received { name: 'pngquant',
  url: 'https://raw.github.com/sindresorhus/node-pngquant-bin/v0.1.7/vendor/linux/x64/pngquant' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at /root/romana/manage/node_modules/.npminstall/download/0.1.19/download/index.js:35:43
    at each (/root/romana/manage/node_modules/.npminstall/each-async/0.1.3/each-async/each-async.js:63:4)
    at module.exports (/root/romana/manage/node_modules/.npminstall/download/0.1.19/download/index.js:33:5)
    at BinWrapper._download (/root/romana/manage/node_modules/.npminstall/bin-wrapper/0.2.4/bin-wrapper/index.js:283:14)
    at BinWrapper.check (/root/romana/manage/node_modules/.npminstall/bin-wrapper/0.2.4/bin-wrapper/index.js:75:10)
    at /root/romana/manage/node_modules/.npminstall/pngquant-bin/0.1.7/pngquant-bin/index.js:27:5
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
make[1]: *** [build-stamp] Error 7
make[1]: Leaving directory `/root/romana/manage'
make: *** [build-ui] Error 2
FAIL: 2
```

**Comment by gitbeyond** [comment]
# wget https://raw.github.com/sindresorhus/node-pngquant-bin/v0.1.7/vendor/linux/x64/pngquant
# yum install libpng12-devel libpng12 libpng-devel libpng
# cp pngquant /sbin/
as pngquant ,you may still need download
 optipng, jpegtran
